stages:
  - build
  - test
  - deploy

variables:
  MOD_ID: "creature-mod"
  JDK: "21"

build-job:
  stage: build
  image: gradle:jdk21
  script:
    - chmod +x ./gradlew
    - ./gradlew properties
    - export MOD_VERSION=$(grep "^mod_version=" gradle.properties | cut -d "=" -f2-) || echo "MOD_VERSION not found"
    - export MINECRAFT_VERSION=$(grep "^minecraft_version=" gradle.properties | cut -d "=" -f2-) || echo "MINECRAFT_VERSION not found"
    
    # Create build.env if versions are available
    - |
      if [ -n "$MOD_VERSION" ] && [ -n "$MINECRAFT_VERSION" ]; then
        echo "Creating build.env..."
        echo "MOD_VERSION=${MOD_VERSION}" > build.env
        echo "MINECRAFT_VERSION=${MINECRAFT_VERSION}" >> build.env
      fi
    
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month

test-job:
  stage: test
  image: gradle:jdk21
  script:
    - ./gradlew test
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  image: gradle:jdk21
  script:
    - mkdir -p mods
    - cp build/libs/*.jar mods/
    - echo "Mod built and deployed to mods folder"
  only:
    - main